language: android
jdk: oraclejdk7
cache: false
env:
  global:
    - ADB_INSTALL_TIMEOUT=10
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository
before_script:
  - chmod +x gradlew
script:
  - ./gradlew clean
  - ./gradlew :domain:test --continue
  - ./gradlew build
